[package]
name = "traffic_simulator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
paho-mqtt = "0.9"
env_logger = "0.9"
log = "0.4"