version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iot
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./influxdb_template:/var/opt/influxdb_template:ro
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

  webapi:
    image: webapi
    ports:
      - "11443:443"
      - "11080:80"
    restart: always
    depends_on:
      - influxdb
    networks:
      - iot
    environment:
      - INFLUXDB_ORGANIZATION=${INFLUX_ORG}
      - INFLUXDB_BUCKET=${INFLUX_BUCKET}
      - INFLUXDB_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUXDB_URL="http://influxdb:8086"

  frontend:
    image: hz-siemens-fe
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - influxdb
    networks:
      - iot

  anomaly_analyze:
    image: anomaly_analyze
    restart: always
    depends_on:
      - influxdb
    networks:
      - iot
    environment:
      - INFLUXDB_ORGANIZATION=${INFLUX_ORG}
      - INFLUXDB_BUCKET=${INFLUX_BUCKET}
      - INFLUXDB_TOKEN=${INFLUX_ADMIN_TOKEN}

  disruption_prediction:
    image: disruption_prediction
    restart: always
    depends_on:
      - influxdb
    networks:
      - iot
    environment:
      - INFLUXDB_ORGANIZATION=${INFLUX_ORG}
      - INFLUXDB_BUCKET=${INFLUX_BUCKET}
      - INFLUXDB_TOKEN=${INFLUX_ADMIN_TOKEN}

networks:
  iot:

volumes:
  influxdb-data:
  grafana-data:
