name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      INFLUX_USERNAME: ${{ secrets.INFLUX_USERNAME }}
      INFLUX_PASSWORD: ${{ secrets.INFLUX_PASSWORD }}
      INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
      INFLUX_ADMIN_TOKEN: ${{ secrets.INFLUX_ADMIN_TOKEN }}
      INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: make build
    - name: Bring the system up
      run: make compose_up
    - name: Feed some traffic into the system
      run: make run_simulator
    - name: Cleanup
      run: make compose_down clean
